### ISSUE TITLE
希望可以增加以圖搜圖網站

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#10]
如題，希望以圖搜圖可以增加 https://ascii2d.net 為其中一個搜圖網站

**Comment by AInoob** [comment]
Hello，感谢建议，这个网站之前也有人推荐了，会放到to-do的，不过最近工作比较忙，功能性的暂时不会增加，主要修复bug～

**Comment by AInoob** [comment]
已经增加Ascii2d.net，感谢提供的建议！然后，如果喜欢二箱，欢迎推荐给盆友们哦～
