### ISSUE TITLE
Arch Linux不能正常使用

### ISSUE THREAD

**Issue by dafeinayius** [AInoob/NooBox#100]
使用Arch Linux kde版本，chrome浏览器，使用以图搜图功能选择本地图片并确定后，没有任何网页和搜索结果打开

**Comment by AInoob** [comment]
Hello，这个是linux下Chrome的问题，我这里deepin linux 也是一样的。Windows下没有问题。所以如果想本地搜索目前只能用骚操作，地址栏输入这个: chrome-extension://kidibbfcblfbbafhnlanccjjdehoahep/popup.html
