### ISSUE TITLE
图片搜索结果里面的google相关链接无法点击打开

### ISSUE THREAD

**Issue by jackcczqs** [AInoob/NooBox#102]
**描述 Bug*
Bug 的具体状况是什么样的
搜索结果的google相关链接无法直接点击跳转
**期望的行为是怎么样的**
正常的行为应该如何的
点击标题链接直接跳转
**截图**
如果有Bug 截图可以提供，最好提供一下
![image](https://user-images.githubusercontent.com/61110090/74603239-74c82880-50ec-11ea-9ac7-47edcc70e09e.png)

**平台 (提供完整信息):**
 - 浏览器 [e.g. Chrome，QQ浏览器，360 极速浏览器等等]
Chrome
**额外信息**
其他信息需要我们知道的

**Comment by AInoob** [comment]
的确是。。。感谢反馈～

最近谷歌一直不通过我的拓展，不知道什么时候才能更新。。。

**Comment by AInoob** [comment]
新版本已经写完，发布估计要几天，如果运气不好。。。可能要过很久很久

**Comment by mutageneral** [comment]
I am sorry I don't speak Chinese and I want to make sure, this is talking about how it doesn't work with google images search and tiny eyes right? I also had problems with bing images sometimes. If it's not about that problem then I will open an issue about it.

**Comment by AInoob** [comment]
Hello，已经修复了~

**Comment by AInoob** [comment]
> I am sorry I don't speak Chinese and I want to make sure, this is talking about how it doesn't work with google images search and tiny eyes right? I also had problems with bing images sometimes. If it's not about that problem then I will open an issue about it.

Hi, Google issue is fixed, Tineye updated their API, so it's not possible to get result from them now...

**Comment by AInoob** [comment]
Version 1.1.7, which should be approved by Chrome web store in next few days.

版本1.1.7，应该会在几天内通过审核。
