### ISSUE TITLE
火狐扩展下架了？

### ISSUE THREAD

**Issue by Nojike** [AInoob/NooBox#103]
**描述 Bug*
Bug 的具体状况是什么样的

**期望的行为是怎么样的**
正常的行为应该如何的

**截图**
如果有Bug 截图可以提供，最好提供一下

**平台 (提供完整信息):**
 - 浏览器 [e.g. Chrome，QQ浏览器，360 极速浏览器等等]

**额外信息**
其他信息需要我们知道的

**Comment by Nojike** [comment]
忘了说是linux。

**Comment by AInoob** [comment]
好像是的。。。明天看看

**Comment by AInoob** [comment]
Hello，应该已经上架了，感谢反馈～
