### ISSUE TITLE
選單翻譯還有英文

### ISSUE THREAD

**Issue by RealRow** [AInoob/NooBox#104]
![image](https://user-images.githubusercontent.com/52208181/77943314-99204300-72ef-11ea-98ab-09b718192144.png)
![image](https://user-images.githubusercontent.com/52208181/77943399-bb19c580-72ef-11ea-99bb-cfc4bdc5cbe3.png)

如圖，選單還有英文
我記得這個是已翻譯的

還有這個
![image](https://user-images.githubusercontent.com/52208181/77943492-e00e3880-72ef-11ea-9020-b56527d21262.png)

紅框處的文字點了也沒辦法直接到github
右鍵newtab中開啟倒是可以

------

另有問題

翻譯修正要fork ts通道，再pull修正嗎？

**Comment by AInoob** [comment]
嗨，感谢建议。请问问题现在还存在吗？如果存在我争取这周末更新一下~

**Comment by zhtw2013** [comment]
@AInoob 還存在

**Comment by AInoob** [comment]
Hi，再次犯懒了。。。这周末会更新一下

**Comment by AInoob** [comment]
> Hi，再次犯懒了。。。这周末会更新一下

并没有。。。下周更新一下手机版，同时会更新这个的。不好意思。

**Comment by AInoob** [comment]
Hello, 已经更新了，版本1.1.8，估计各个商店需要一段时间才能上架。
感谢反馈～
