### ISSUE TITLE
新版不支持拖拽上传了吗

### ISSUE THREAD

**Issue by kingokksa** [AInoob/NooBox#105]
之前版本都可以，新版不知道为什么传不了了

**Comment by AInoob** [comment]
请问是可以了吗？我在Window下面Chrome可以。

**Comment by kingokksa** [comment]
> 请问是可以了吗？我在窗口下面Chrome可以。
嗯嗯可以了，我不知道怎么删掉这个issue😂

**Comment by AInoob** [comment]
> > 请问是可以了吗？我在窗口下面Chrome可以。
> 嗯嗯可以了，我不知道怎么删掉这个issue😂

没事没事，已经close了～
