### ISSUE TITLE
无法调用搜索结果图片

### ISSUE THREAD

**Issue by Ainrie** [AInoob/NooBox#106]
**描述 Bug*
在使用NooBox搜索的时候，谷歌和百度显示红色无效，但我点击谷歌图标进去后是可以正常搜索图片的，百度显示网址错误

**截图**
![image](https://user-images.githubusercontent.com/63640523/79208405-920f3e00-7e74-11ea-9c5c-993d00261ca3.png)
![image](https://user-images.githubusercontent.com/63640523/79208439-9d626980-7e74-11ea-9a4c-c0f5aa4ee8b1.png)
![image](https://user-images.githubusercontent.com/63640523/79208480-ace1b280-7e74-11ea-968c-83d193272956.png)

**平台 (提供完整信息):**
 - Chrome浏览器

**Comment by AInoob** [comment]
感谢反馈，谷歌和Yandex都已经修复了~
版本1.1.7，已经上传，大概几天后会通过审核。到时如果还是不行，请告知~
