### ISSUE TITLE
Yandex can't load the image when using screen capture

### ISSUE THREAD

**Issue by DarkRoku12** [AInoob/NooBox#107]
**Describe the bug**
Yandex can't load the image, nor by Noobox HTTP link or using the noobox url generateds when using the screen capture feature

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera, Vivaldi.
 - Version: 1.1.6 (lastest from Chrome store)

![image](https://user-images.githubusercontent.com/12215749/79306400-2607f680-7ec3-11ea-8c57-0039be62a20e.png)

Then link not working:

![image](https://user-images.githubusercontent.com/12215749/79306348-0b358200-7ec3-11ea-9b1f-f242cc8356e4.png)

Even if you do this the search fails:

![image](https://user-images.githubusercontent.com/12215749/79306452-391ac680-7ec3-11ea-9f1b-111ef1b89211.png)

The result is the same:

![image](https://user-images.githubusercontent.com/12215749/79306481-4a63d300-7ec3-11ea-8c20-2f39267f1282.png)

The problem only happens when using the screen capture, so noobox uploads the cropped image to its server and then the noobox api link is not recognised by yandex.

**Comment by AInoob** [comment]
Hi, the image link will expire after a while, so you need to re-search or upload it again.
