### ISSUE TITLE
建议，适配Edge浏览器

### ISSUE THREAD

**Issue by guilin007** [AInoob/NooBox#109]
**描述 Bug*
Edge浏览器商店无法搜索

**期望的行为是怎么样的**
可以通过Edge浏览器商店进行安装

**截图**
如果有Bug 截图可以提供，最好提供一下

**平台 (提供完整信息):**
Edge浏览器

**额外信息**
其他信息需要我们知道的

**Comment by AInoob** [comment]
Hi，感谢建议~

Edge暂时不考虑了。。。如果你说的是Chromium版本的Edge，现在其实已经兼容了，我只需要打包上传。

**Comment by MXSZZ4526** [comment]
> Hi，感谢建议~
> 
> Edge暂时不考虑了。。。如果你说的是Chromium版本的Edge，现在其实已经兼容了，我只需要打包上传。

希望打包上传一下Chromium版本的Edge商店上，现在Edge扩展商店里搜索不到~

**Comment by AInoob** [comment]
嗯，之前上架被微软拒绝了，一气之下就好久没有弄。。。争取这周末更新一下。。。嗯。争取。

**Comment by AInoob** [comment]
> > Hi，感谢建议~
> > Edge暂时不考虑了。。。如果你说的是Chromium版本的Edge，现在其实已经兼容了，我只需要打包上传。
> 
> 希望打包上传一下Chromium版本的Edge商店上，现在Edge扩展商店里搜索不到~

嗯，之前上架被微软拒绝了，一气之下就好久没有弄。。。争取这周末更新一下。。。嗯。争取。

**Comment by MXSZZ4526** [comment]
> > > Hi，感谢建议~
> > > Edge暂时不考虑了。。。如果你说的是Chromium版本的Edge，现在其实已经兼容了，我只需要打包上传。
> > 
> > 
> > 希望打包上传一下Chromium版本的Edge商店上，现在Edge扩展商店里搜索不到~
> 
> 嗯，之前上架被微软拒绝了，一气之下就好久没有弄。。。争取这周末更新一下。。。嗯。争取。

哈~ 原来是被微软审核给拒了~  先谢了，大哥有空就弄吧~

**Comment by AInoob** [comment]
@guilin007 @MXSZZ4526 

https://microsoftedge.microsoft.com/addons/detail/noobox/jacoeejpmihiopgohinegbiekdombfde

上架了～
