### ISSUE TITLE
NooBox doesn't work for images in Chrome Dev 62

### ISSUE THREAD

**Issue by LenKiMo** [AInoob/NooBox#11]
Windows 10 & Chrome Dev 62.0.3202.9 64-Bit

If user right-clicks in a image, NooBox will not appear in the context menu. For example:
https://i.loli.net/2017/09/10/59b49735a833d.png

But it will appears when right-click for a link. Example in here:
https://i.loli.net/2017/09/10/59b497520e80e.png

I don't know if this is a change from Chrome's limit for extension. But please keep an eye on it.

**Comment by AInoob** [comment]
This is interesting, can you please show me the background output? Here are steps:
1. Go to Chrome extensions page
2. Click developer mode
3. Find NooBox and click inspect view: background.
4. Click console
5. Screenshot and paste the console logs,
here is mine:
![image](https://user-images.githubusercontent.com/7615460/30246522-82e0bd86-95b1-11e7-9e41-39aa4e20d9a4.png)

**Comment by LenKiMo** [comment]
Nothing in it.

This is what I see:
https://i.loli.net/2017/09/10/59b4f8332a332.png

To confirm whether I opened a wrong window or not, that's what I see in `Element` tab:
https://i.loli.net/2017/09/10/59b4f833293d5.png

As complementary information, other image search extension like `Image Search Options` provided by SauceNao also disappear in Chrome Dev. Only build-in Google image search and Ascii2d search extension can works right.

**Comment by bestpika** [comment]
這問題跟我底下那個一樣，原來 62 開始就不正常了

**Comment by AInoob** [comment]
@LenKiMo This is interesting, I think I have a clue now, will investigate soon(should be done by the end of today PT time)

**Comment by AInoob** [comment]
@LenKiMo 
1. Can you please tell me if extract images works or not? Since I cannot reproduce the issue(I have tried Canary version & old version), it's not easy for me to investigate.
2. Can you make sure if reverse image search is turned on in Options page?

**Comment by LenKiMo** [comment]
By disable all of my extensions and re-enable them one by one, I can confirm it is due to NooBox has compatibility problem with [Ascii2d Image Search](https://chrome.google.com/webstore/detail/ascii2d-image-search/dlnbkfiafmkajgbhpdfmkeljamdlfelo) extension. When Ascii2d and NooBox enable synchronously, Ascii2d will cover NooBox so that user can't find NooBox in context menu.

I suspect if this is Chrome's design or bug, to only allow a limit extension appears in context menu. Because other

And I had done the test in my Flags' setting, I can't confirm whether Chrome's Flags setting will affect this too, or not.

**Comment by AInoob** [comment]
@LenKiMo Thank you so much for figuring this out! 
In my case, having Ascii2d and NooBox both enabled does not hide any one's context menu, so I do not think I can do much about it.
I will put Ascii2d in to-do list, since so many people have told me about this, hopefully I will be free next weekend and add Ascii2d into search engines. :)

**Comment by LenKiMo** [comment]
I had downloaded a clean Chrome Dev ( 62.0.3198.0 32-Bit) to test.
When enable SauceNao and NooBox, NooBox will cover SauceNao, when enable Ascii2d, it will cover NooBox. Maybe it is Chrome's change but still some doubts.

I had sent a feedback to Chrome Forum and wait for reply. For now we only can arrive here.

**Comment by AInoob** [comment]
Awesome, thank you!
