### ISSUE TITLE
點「以圖搜圖」沒有反應

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#14]
背景頁面的錯誤訊息如圖
總覺得是 key 錯 function 名…
![image](https://user-images.githubusercontent.com/5698157/30527297-98778a2c-9c59-11e7-868f-55dd7d102f89.png)

**Comment by Nojike** [comment]
问题同上。

**Comment by AInoob** [comment]
好严重的问题，马上修复

**Comment by bestpika** [comment]
目前 ok 了，謝謝
