### ISSUE TITLE
繁体漏翻的地方....

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBox#15]
我的失误..没注意到util.js里还有文本，抱歉抱歉...
繁体用的时间显示，如果还有漏翻请告诉我...

["剛剛","片刻後"],["%s秒前","%s秒後"],["1分鐘前","1分鐘後"],["%s分鐘前","%s分鐘後"],["1小時前","1小時後"],["%s小時前","%s小時後"],["1天前","1天後"],["%s天前","%s天後"],["1週前","1週後"],["%s週前","%s週後"],["1月前","1月後"],["%s月前","%s月後"],["1年前","1年後"],["%s年前","%s年後"]

二箱Chrome商店介绍翻译
------

一個實用的工具箱！多搜尋引擎以圖搜圖+擷取圖片+擷圖搜尋+HTML5影片控制

一個實用的工具箱！多引擎 以圖搜圖+擷圖搜尋+擷取圖片

目前有：
  圖片
    以圖搜圖
      Google引擎
      百度引擎
      Tineye引擎
      Bing引擎
      Yandex引擎
      IQDB引擎
      SauceNao引擎
    擷取圖片
    擷圖搜尋

最近更新:
2017-09-17
    加入Ascii.net！
    修復以圖搜圖引擎位址bug
2017-09-10
    增加了中文繁體，超級感謝zhtw2013
2017-08-13
    修復版本Bug
2017-08-13
    修復擷取圖片大Bug
2017-08-11
    修復相容性問題
2017-07-22 
    修復擷取圖片bug
    增加基礎說明
    更新檢查更新
    變更錯別字
    刪除無用語法
    可以刪除單條記錄了
2017-07-20 
    再次修復HTML5影片控制bugs
    修復以圖搜圖排序bug
2017-07-16
    修復HTML5影片控制bugs
    修復拖曳上傳搜尋
2017-06-28
    修復上傳bug，使用AInoob的伺服器啦~
2017-06-25
    修復百度bug
    Production模式，更快！
2017-06-18
    修復上傳bug
2017-03-06
    修復歷史記錄bug
2017-03-04
    修復HTML5影片控制bug
    加入歷史記錄開關
    修復擷取圖片權限bug
2017-02-24
    修復HTML5影片控制的bug
2017-02-20
    修復UI的bug，改進UI
2017-02-18
    刪除Chrome線上商店的檢查更新
    擷取圖片增加下載選項
    修復Google獲取的bug
    刪除致命搜尋結果bug
    修復擷取圖片增加下載bug
2017-02-11
    增加版本更新提示
    修復顯示bug
2017-02-10
    增強對舊核心的支援
2017-02-09
    增加HTML5影片控制(alpha版本)
2017-02-07
    修復圖片取得函數bug
2017-02-04
    修復擷取圖片右鍵bug，增加HTML5 影片控制（未開放）
2017-01-30
    修復歷史記錄bug，修復顯示bug
2017-01-28
    修復顯示bug
2017-01-25
    修復擷取圖片bug，加入連結圖片篩選
2017-01-14
    修復analytics bug
    更新提取圖片UI
2017-01-13
    修復錯別字

詳細更新記錄:
https://github.com/AInoob/NooBox/commits/master

-------
二管家的商店介紹等等會發過去二管家那裡。

**Comment by AInoob** [comment]
Util都被发现了，哈哈，话说你这个繁体也太猛了，不用这么热心的～ 哈哈

感谢！
