### ISSUE TITLE
IQDB 返回的結果排版亂了、部分圖示無法顯示

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#18]
怕踩到版權問題所以中間的圖我只留一部份
![image](https://user-images.githubusercontent.com/5698157/32714278-1107e20c-c888-11e7-8c0a-87cd446ed95f.png)

另外還有一些看起來是圖示的無法顯示，在控制台看到的錯誤如下，實際問題上面那張也有
![image](https://user-images.githubusercontent.com/5698157/32714332-4cf17c92-c888-11e7-85eb-f43ff02628e4.png)

**Comment by AInoob** [comment]
感谢反馈，最近比较忙，预计3天后解决~

**Comment by bestpika** [comment]
圖示的部分目前好像還是有問題

**Comment by AInoob** [comment]
哈哈，一直没有解决，不好意思。

其实一部分原因是自己把动漫的都关掉了，所以一直没注意。。。
会争取和你的另一个想法一起更新的，再次感谢反馈！

**Comment by bestpika** [comment]
@AInoob 不好意思缺的 icon 可以先補上嗎 QQ

**Comment by AInoob** [comment]
嗨，应该已经修复了，如果没有，欢迎reopen。
抱歉拖这么就才修复（其实可能早修复了？）
