### ISSUE TITLE
Could this be turned into a tampermonkey script etc? to not limit to just and extension?

### ISSUE THREAD

**Issue by dyingjedi** [AInoob/NooBox#19]
Could this be turned into a tampermonkey script etc? to not limit to just and extension?

Say using Adguard Extensions load this up and while running #Adguard in the awesome proxy mode every website you visit can now use NooBox functions?

**Comment by dyingjedi** [comment]
? is this an outta sorts question?

**Comment by AInoob** [comment]
Unlikely, I don't think userscripts have enough permission to do CORS things. And right now I am not actively updating NooBox, so even if this happen, it will not be in a near future.
