### ISSUE TITLE
Google搜图提示错误

### ISSUE THREAD

**Issue by ovear** [AInoob/NooBox#2]
图片太大或网速太慢，因此无法下载。

另外插件所用的图床是开发者自己的么？

http://chuantu.biz/

能否不使用图床呢

**Comment by AInoob** [comment]
感谢反馈，图床不是自己的，都是网上找的免费的。我也在想要不要自己弄。
http://chuantu.biz/ 的确有不少问题，默认其实是postimg，可能你被墙了，所以就自动选到http://chuantu.biz/ 了
我会想办法的，目前正在写HTML5 Video Control

**Comment by AInoob** [comment]
已经修改为自己的图床，会保存图片一段时间，然后自动删除
