### ISSUE TITLE
Chrome Web Store 版本無更新

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#22]
請問一下後來的版本是不是沒有放到 Chrome Web Store 上啊？
上面的版本一直停在 `0.9.4.3`

**Comment by zhtw2013** [comment]
事實上作者個人網站的版本也沒更新，新版可能還未完成吧。

**Comment by bestpika** [comment]
可是他在套件的某個人的問題底下回覆說更新到 0.9.4.4 讓我一直很疑惑 XD
![image](https://user-images.githubusercontent.com/5698157/34105778-9ec226d4-e430-11e7-8478-38b80faa9cdf.png)

**Comment by AInoob** [comment]
更新过新的版本了~
