### ISSUE TITLE
無法使用「清空所有歷史」功能

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBox#25]
src/popup/About.jsx

這裡的敘述寫錯了
![image](https://user-images.githubusercontent.com/9501406/34460903-3e4cc2a6-ee57-11e7-8ab5-e700ce67b909.png)

應該是二箱才對，不是二管家。

另外語言檔，「清空所有歷史」字串請改為「清除所有歷程」
感謝您~

「在前臺打開新的標簽」請改為「在前景新分頁開啟」
![image](https://user-images.githubusercontent.com/9501406/34460982-92595cb8-ee59-11e7-8e01-fb487dfcbcb8.png)

Yes No
是 否  
沒有翻到
![image](https://user-images.githubusercontent.com/9501406/34460949-a6196cb2-ee58-11e7-808a-eb8a3997f8db.png)

**Comment by AInoob** [comment]
清空历史这个bug已经修复了，翻译的问题会放到下次更新啦~

**Comment by zhtw2013** [comment]
感謝

**Comment by zhtw2013** [comment]
@AInoob 大佬,翻譯沒有一同更新阿！！！
