### ISSUE TITLE
关于功能建议[图片尺寸筛选]

### ISSUE THREAD

**Issue by dimonwei** [AInoob/NooBox#3]
非常喜欢这个插件,但是发现在搜出来图后无法进行

> 图片的尺寸或者文件大小的筛选

操作,,我认为如果有这个功能会让找图片变得十分方便,特别是找到原图,,希望作者能够加入筛选功能,再次感谢提供这么一个十分有用的插件:)

**Comment by AInoob** [comment]
你好，应该是可以按照大小排序的啊，还是你说的是提取图片？

**Comment by AInoob** [comment]
天！大小竟然没了！！！会在一个小时内修复的，感谢支持！

**Comment by AInoob** [comment]
昨天已经修复，感谢支持

**Comment by dimonwei** [comment]
cool   看到已经修复 非常感谢 💯

**Comment by AInoob** [comment]
哈哈，感谢支持！如果很喜欢的话，可以推荐给盆友们哟~
然后提取图片功能最近增强了，后续会继续加强~
