### ISSUE TITLE
[Suggestion] Possible rework/improvement of the "screenshot search" function?

### ISSUE THREAD

**Issue by erasedff** [AInoob/NooBox#32]
This extension is great but "screenshot search" function feels very clunky dated in terms of design.
It would be nice if this feature was reworked and improved in the future. For example make it look and behave similarly to the native Firefox screenshot tool:
https://i.imgur.com/X3TlTuP.gifv
Or maybe something similar to ShareX.
I don't think element highlight (on hover) and image share/upload are necessary but it would be nice to have "save/copy to clipboard" function (along with the obvious "image search" button).

**Comment by MaMaMiY** [comment]
Definitely, we have lots of new idea on screenshot search and will add a cool screen shot feature in the feature.
