### ISSUE TITLE
0.9.6.1版本

### ISSUE THREAD

**Issue by 715670119** [AInoob/NooBox#35]
额……不小心关闭了上个话题，，另一个用户反馈360安全浏览器也装不了这个最新版，我这个搜狗也是的，，我这个搜狗的版本是搜狗论坛的9周年新版本，并非正式版，正式版的内核很落后了，你可以下载个论坛9周年的搜狗新核版本来试试这个插件，我反正是浏览器闪退状态。

**Comment by MaMaMiY** [comment]
好的我去试试一下，你的环境是windows 还是mac os ？
我们会尽力处理的

**Comment by 715670119** [comment]
win10

**Comment by MaMaMiY** [comment]
我测试了正式版的搜狗，刚才从官网下的，好像没有崩溃，搜了几个图片都可以。 我的安装源是chrome商店，能不能发给我个你下载 9周年的地址，我去下载一下

**Comment by MaMaMiY** [comment]
我测试了一下最新的360浏览器也可以，我能问下你之前都是怎样下载安装包的吗？我是下了一个360安全卫士装上用里面的那个管家安装的

**Comment by 715670119** [comment]
http://pinyin.sogou.com/bbs/forum.php?mod=viewthread&tid=2710110这是9周年论坛新核测试版链接，我下载的插件，是从二箱官网下载的，那个crx单独下载，，然后直接拖入9周年搜狗，，，搜狗装插件都是直接拖入。

**Comment by MaMaMiY** [comment]
好的，我去试试从我们网站上的地址下载试试，不过我把我下载地址贴给你，你去试一下？
https://chrome.google.com/webstore/detail/noobox/kidibbfcblfbbafhnlanccjjdehoahep

**Comment by 715670119** [comment]
我去谷歌商店，下载0.9.6.1,嗯，完全可以安装…………那么问题来了，谷歌商城的和二箱官网的，不是一个插件吗

**Comment by MaMaMiY** [comment]
应该是一个，之前为了方便国内用户无法下载这边的，新弄的一个包，可能是某个push 文件没有弄全导致的，最近我跟ainoob都特忙，有时间了我们会重新整合一下，🙏谢谢
