### ISSUE TITLE
語言包疑問

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBox#38]
![image](https://user-images.githubusercontent.com/9501406/44026191-d1357062-9f24-11e8-8bdf-1bc188626bb9.png)

這個部分是不是寫錯了 應該是message7?

我看英文是這樣，結果中文有兩個6...

**Comment by AInoob** [comment]
是的，10分钟后修复，感谢反馈！

**Comment by AInoob** [comment]
已经更新，感谢反馈
