### ISSUE TITLE
右鍵功能表順序

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#39]
您好，新版右鍵功能表的以圖搜圖功能改順序到第二個的原因可以問一下嗎？
因為已經很習慣按第一個了現在改了很常按錯…

**Comment by AInoob** [comment]
恩恩，会在下一个版本恢复的。目前的解决办法是在关闭所有图片搜索，然后一次打开功能。但是重启就会丢失。大概24小时之内恢复。On Aug 13, 2018 4:51 AM, Yui Mitsuki <notifications@github.com> wrote:您好，新版右鍵功能表的以圖搜圖功能改順序到第二個的原因可以問一下嗎？
因為已經很習慣按第一個了現在改了很常按錯…

**Comment by AInoob** [comment]
已经更新，感谢反馈

**Comment by bestpika** [comment]
`v1.0.9` 的順序又變了 XD

**Comment by AInoob** [comment]
尴尬，我们merge出现了问题，马上修复~
