### ISSUE TITLE
能给我发一份旧版文件吗

### ISSUE THREAD

**Issue by shitou666999** [AInoob/NooBox#40]
我没找到，新版我用不习惯，还是喜欢旧版，希望帮助一下，谢谢。

**Comment by RageCoke1466** [comment]
新版哪里用的不习惯呢？我们马上更新我们的文档了，会有一个说明

**Comment by AInoob** [comment]
Hello，旧的可以在这里下载：https://ainoob.com/api/file/noobox/NooBox_0.9.6.1.crx

然后新的肯定会继续优化的
