### ISSUE TITLE
搜尋結果問題

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#41]
1. 有的時候會有一種標題寫著「Possible Match」但是點下去連結卻是 `chrome-extension://kidibbfcblfbbafhnlanccjjdehoahep/searchResult.html` 的結果
1. 有時網址會出現 `httpshttp://e-shuushuu.net/image/{這裡是數字}/`
1. 有時網址會出現 `chrome-extension://kidibbfcblfbbafhnlanccjjdehoahep/https//konachan.com/post/show/{這裡是數字}`
1. 有的結果會顯示成這樣
  ![image](https://user-images.githubusercontent.com/5698157/44077158-45ab84e4-9fd5-11e8-8cb2-2a5e51daa919.png)

**Comment by RageCoke1466** [comment]
可能是處理的鏈接是內部鏈接但是我們沒有做轉換，能不能告訴我是哪個引擎出的問題，我們把問題收集一下，這個周末全部修復，因為新版本是全部重寫，可能是有些bug。

**Comment by bestpika** [comment]
看起來都是 IQDB 的問題

**Comment by RageCoke1466** [comment]
问题 应该解决一半了，我们已经push了一个新的版本上去，我会再花点时间看看遇到的那个extension 链接，IQDB 这个网站挺不规范的

**Comment by RageCoke1466** [comment]
不好意思之前沒註意用的簡體回答的問題，我再來一遍，“問題 應該解決一半了，我們已經push了一個新的版本上去，我會再花點時間看看遇到的那個extension 鏈接，IQDB 這個網站挺不規範的”

**Comment by bestpika** [comment]
用簡體無妨，我看得懂 XD

**Comment by RageCoke1466** [comment]
XD
