### ISSUE TITLE
最近更新的那一版不好用了...........

### ISSUE THREAD

**Issue by 990721830** [AInoob/NooBox#43]
![snipaste20180818_033649](https://user-images.githubusercontent.com/25548230/44285523-4cadfe00-a298-11e8-9f49-b8183e7c7e2d.jpg)
上次自动更新了.......
没有之前那一版排版好了.....
而且卸载之后直接从商店安装无法用了......
先换回旧版的了,,,,

大佬还有你有没有兴趣做一个【可自定义的聚合搜索引擎】的脚本或者拓展
下面是我上次写得简书........
https://www.jianshu.com/p/33f00a79e1e8

**Comment by RageCoke1466** [comment]
让我看一下，我在我的电脑上好像没有这样的情况  ？ 我们现在在 优化 新的版本，新版本在变的越来越稳定，我们的新版本版本排版有哪些地方用起来不习惯吗 ？ 可以截一个你用的新版本搜索结果的图吗 ？可以先切回之前的版本，新版本我们会再优化的，现阶段接到的埋怨是，我们没有把原来的 相关性加入新的引擎中，我们会在以后添加，请问你遇到的是这个情况吗 ？

**Comment by RageCoke1466** [comment]
对了等一下，你的浏览器是不是不是Chrome ？

**Comment by 990721830** [comment]
360极速啊.......
刚试了下cent也是安装不了......

**Comment by RageCoke1466** [comment]
这个原因我感觉跟内核有关系，我看了一下的项目感觉很有意思，已经下载安装表示支持！哈哈哈，我之前有跟ainoob讨论要不要加入聚合搜索，但是我们想先把图片做好

**Comment by RageCoke1466** [comment]
我的电脑是Mac os 没法测试 360极速，你现在在国外还是在国内。 我看了360 极速浏览器 ！，他们好像换了内核，不是chrome了变成了blink 
![image](https://user-images.githubusercontent.com/12090689/44291470-8fe27f80-a24c-11e8-991c-e6b5de80f225.png)

**Comment by 990721830** [comment]
国内啊.......
极速chrome63内核啊
cent 67 内核

**Comment by RageCoke1466** [comment]
虽然chrome 用的也是blink ，我测试用的Chromium的 QQ mac 浏览器是可以的跑noobox的

**Comment by 990721830** [comment]
有没有建一个QQ群啊......
方便交流啊.....
下次做聚合搜索的时候我还有N多建议呢....

**Comment by RageCoke1466** [comment]
我们在考虑，Master 的readme 已经删了打算重写，但是可能在新版本稳定之后，新版本用了比较好的构架，但是我们也在摸索，新版本的搜索结果页有什么建议吗 ？哪里用起来不舒服，

**Comment by RageCoke1466** [comment]
对了 我刚才去360极速浏览器论坛喵了一眼，360极速浏览器还是32位的 ？跟这个有没有关系呢 ？

**Comment by RageCoke1466** [comment]
感谢你的建议！ 谢谢你，嘿嘿

**Comment by 990721830** [comment]
![snipaste20180818_065056](https://user-images.githubusercontent.com/25548230/44291776-26498c00-a2b3-11e8-90f9-29e38499d667.jpg)
 cent 64位不行
chrome 32和64刚试了都说无法解压程序......

**Comment by RageCoke1466** [comment]
我找个电脑去确认一下windows版的chrome，给我15分钟，新版本的搜索结果页有哪些不习惯能告诉我下吗 ？

**Comment by 990721830** [comment]
我已经忘记那个界面了....
但是界面背景可以调成偏灰的......

**Comment by RageCoke1466** [comment]
![image](https://user-images.githubusercontent.com/12090689/44292102-e782ea00-a250-11e8-8613-76fea5a7af34.png)
这是我们新的搜索结果页面，还真的是！我发现windows就有问题。。。 我的mac os 没有这个问题，这个问题可能要联系Chrome web store 团队，我给他们发个邮件

**Comment by RageCoke1466** [comment]
关于新版本搜索引擎的变化 旧版本 google 5张 baidu 爆炸 bing 一张 新版本 google 最多能有90张，百度 最多也能有30多张，bing 也是能有几十张。 但是量上来了确实要优化处理方式

**Comment by 990721830** [comment]
本可儿要睡觉啦(=・ω・=)

**Comment by RageCoke1466** [comment]
哈哈哈！，好的晚安，通宵 report bug，我们真是感激不敬！

**Comment by SaberZoe** [comment]
为啥最新的二箱不能用了.....有交流群吗.......

**Comment by SaberZoe** [comment]
插件安装不上去

**Comment by RageCoke1466** [comment]
统一回复 https://github.com/AInoob/NooBox/issues/44
