### ISSUE TITLE
统一回复Noobox新版本为什么不能安装了, Unified Reply Why People Can Not Install New Version

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#44]
因为 Noobox 上一周发布了改动极大的版本，而我们没有准备好应对出现的Bug，让用户产生了不必要的麻烦，

> **我们在这里道歉了 ！**

最近两天Extension 无法被下载或者出现解压错误是因为Web Store 在审核我们的项目，原因我们暂时不知道，但是可能是因为最近一周我们一直在频繁更新，周四晚上一口气直接连续更新了4个版本导致的。
所以我们要等待一周的审核。

如果新版的Bug出现了困扰，或者实在不喜欢，可以切换回老版本，老版本的链接放在了下面。

最后说一句，我们对我们的新版本有很大信心，当然是在修复bug之后
所以再一次感到抱歉

Noobox released a re-make version last week but we are not ready to deal with the bugs that caused unnecessary trouble for users, *

> *we apologize here!**

The extension couldn't be downloaded or the decompression error occurred during last two days because the Web Store is reviewing our App. We don't know why but it may be that we have been updating frequently in the last week. We updated 4 version consecutively in a row on Thursday night. 
We have to wait for a week to get result.

If the Bug in new version is bothering you all the time and you don't like it anyway. Changing back to old version is a compromising choice and the link for old version is here.

Finally, we are confidence in our new version, of course, **after fixing the bug.**
Sorry for all, of course, again

https://ainoob.com/api/file/noobox/NooBox_0.9.6.1.crx

### 说明更新 08/18/2018  13:10 EST
1. 已经优化了 上传图片卡顿 跟 搜索页面卡顿
2. 修复bug 后的版本等待测试完后，会在下方先贴出链接来弥补我们store 爆炸

Description Update
1. Optimized upload Image Laggy and result page laggy. 
2.After fixing the bug and test, and we will post the link below to make up for our store down.

**Comment by 990721830** [comment]
https://extfans.com/extension-download
用商店链接直下就可以了

**Comment by bestpika** [comment]
我忽然發現要這樣弄有點麻煩還是等上架正常好了 orz

**Comment by AInoob** [comment]
已经通过审核~ 撒花~
