### ISSUE TITLE
這次編譯的是Raynor分支？

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBox#45]
![image](https://user-images.githubusercontent.com/9501406/44468293-78920080-a657-11e8-8e3c-2f7d2d757fb0.png)

![image](https://user-images.githubusercontent.com/9501406/44468300-7e87e180-a657-11e8-88a9-9cf08f199154.png)

大佬，你這次編譯的新版本語言包沒有套用到啊
看了一下還有個Raynor分支，用的是舊版語言包....蛋疼啊

所以這次新編譯的是Raynor分支嗎？

希望可以修正一下繁體語言包的問題啊，不是我沒翻到，
是最新的幾版都用了舊版的語言包...

**Comment by RageCoke1466** [comment]
我们马上开始着手修复这些显示的问题，这次更新比较曲折，因为长时间没有更新 Extension 的图片跟 描述所以一直无法通过审核。

**Comment by RageCoke1466** [comment]
对的，我发现了，新添加的语言包在master上面 =。= 抱歉了，之前那版繁体翻译漏洞百出，我们这个周末优化的时候会移植过去的，下次如果要 发送pull request 就直接发送到 Raynor
