### ISSUE TITLE
1.0.1.3 重要更新 Important Release

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#46]
**还在 1.0.1.0 版本的用户，请尽快更新到1.0.1.3**

### 1.0.1.3 重要更新
**修复**
1. 修复了 历史 加载不出来的 问题
2. 修复了 IQDB Title 链接的问题
3. 修复了再次搜索按钮点击没有反应

**优化**
1. 优化了服务器响应
2. 优化了搜索结果页的响应速度
3. 优化了搜索结果页的排布

**添加**
1. 添加默认相关性排序

**If you are still using version 1.0.1.0
Please update to 1.0.1.3 as soon as possible.**

### 1.0.1.3 Important update
**Repair**
1. Fixed the problem that history can't be loaded.
2. Fixed an issue with IQDB Title links

**Optimization**
1. Optimized server response
2. Optimized the response speed of search results pages
3. Optimized the layout of search results pages

**New Feature**
1. Add default relevance ordering

**Comment by RageCoke1466** [comment]
相关链接 https://github.com/AInoob/NooBox/issues/44

**Comment by 990721830** [comment]
![2018 08 23 08 00 05](https://user-images.githubusercontent.com/25548230/44497250-e4ea1f80-a6aa-11e8-8be1-ad4b5c44984a.gif)

哦....对了二管家我也一直用旧版...
最新版能不能也修复一下比例问题.....
由于我默认设置了全页面缩放120%....
导致偏大了.....
建议缩放100%增加自定义缩放比例....

**Comment by bestpika** [comment]
關於網頁自動刷新
請問計時方式可以增加一個選項是「dom ready」之後再開始下一次計時嗎？

謝謝

**Comment by RageCoke1466** [comment]
这个确实是一个改进的方向，document ready
