### ISSUE TITLE
Ascii2D 搜尋連結問題

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#47]
版本 `1.0.1.3`
![image](https://user-images.githubusercontent.com/5698157/44499602-2c76a880-a6b7-11e8-975d-d8362d211c37.png)
最右邊那個，這個站的搜尋是用 post 圖片網址的方式，但是那個連結點進去卻是這種網址
`https://ascii2d.net/search/urihttps://...`

更新一下
剛剛我看了該站發現該站增加了
`https://ascii2d.net/search/url/圖片網址`
的搜尋方式，所以網址改一下應該就行了

另外希望之前有提過該站有「色合檢索」及「特徵檢索」
請問目前的版本特徵檢索的結果有加入了嗎？

**Comment by AInoob** [comment]
感谢反馈，这个会在周末修复的~
特征这个暂时不会添加，不过会放入todo的。
