### ISSUE TITLE
上方网站favicon区域的一些功能建议

### ISSUE THREAD

**Issue by thelastfantasy** [AInoob/NooBox#49]
1. 右键点击过滤，显隐与该图标对应的搜索结果
2. 拖放功能，拖动图标时自动以上方搜索引擎顺序按组别对搜索结果排序，当搜索结果很多的时候挺需要这个功能的

**Comment by AInoob** [comment]
感谢反馈，第一个建议会尽快实现的。第二个这个感觉属于相关排序里面，这个我们会后续增加自定义、更加好的排序的。

**Comment by AInoob** [comment]
嗨，我现在重看这个看不懂了。。。
可能已经支持/修复了？
没有欢迎reopen.
