### ISSUE TITLE
Suggestion: instructions on the "extract images" dialog

### ISSUE THREAD

**Issue by Corrodias** [AInoob/NooBox#5]
There are 4 controls at the top of the "extract images". I would appreciate an explanation, either here or even in "alt text" when hovering the mouse cursor over the controls, about what they do.

The far right is an X, and it closes the dialog, so that's pretty clear. I'm having trouble figuring out what the other 3 do, though.

The leftmost control is a slider, and the farther right it is, the more images appear, but I don't understand what it's changing, exactly. I don't know *why* more images show up, or why you would ever want fewer than all of the images to be shown.

The next is the "example.com/a.jpg" text with a line or a checkmark through it, which you can toggle by clicking. I have not noticed any effect from changing this.

Finally is a downward, green arrow. Clicking it appears to try to create and save a zip file. I was not sure at first what it does because on YouTube, it was stopping 1 short (12/13) with no error displayed. Now I know what it does, but it should probably display an error message.

This is a handy extension, by the way; thank you for creating and maintaining it.

**Comment by AInoob** [comment]
Hi Corrodias, thank you for this useful feedback! I will try to make a instruction ("i" icon) somewhere which lead to a webpage about what does each component does. I will update this within a month.

**Comment by AInoob** [comment]
Hello there, clearly I didn't keep my promise. However, we are going to release 1.0.0.0 version today, things should be more obvious now.
