### ISSUE TITLE
Chrome Web Store 的更新紀錄

### ISSUE THREAD

**Issue by bestpika** [AInoob/NooBox#56]
如題
上面的更新紀錄還停留在「2017-09-25」
不曉得能不能順便改一下

**Comment by RageCoke1466** [comment]
嗯嗯，繁体中文跟 简体中文的都没有修改，我跟Ainoob暂时的打算是用 github 去维护版本更新

**Comment by bestpika** [comment]
那乾脆把 Chrome web store 那邊的更新記錄刪掉改貼連結可能好一點？

**Comment by RageCoke1466** [comment]
已经更新了，嘿嘿，谢谢提醒！
