### ISSUE TITLE
360极速浏览器装了扩展后打开Google后网址后缀会变成ca。

### ISSUE THREAD

**Issue by Nojike** [AInoob/NooBox#6]
如题，如何解决这个问题？我只想用Google.com.。

**Comment by AInoob** [comment]
Hello，这个二箱没有做什么啊。。。你要不看看是不是你的host还是dns还是什么出问题了？

**Comment by Nojike** [comment]
我在另外一个浏览器安装这个插件也会把goole.com跳转到https://www.google.ca/?gfe_rd=cr&ei=OAZuWdLLIcjj8Ae-64DgCQ类似的地址，不安装的就不跳转。

**Comment by AInoob** [comment]
这个的确不科学。。。我没有处理过。。。所以要是实在不行，你就卸载二箱吧。

因为一直用的Google.com，没有出现过类似问题，所以不知道怎么解决～
