### ISSUE TITLE
【图】能增加划词呼出自定义多重引擎功能或者重新写一个拓展?

### ISSUE THREAD

**Issue by 990721830** [AInoob/NooBox#69]
不知道你有没有兴趣做啊...
你先试用一下...
>希望能增加划词呼出自定义多重引擎功能或者重新写一个拓展二搜?

我想要的类似【SearchBar】的自定义多重搜索引擎跳转...

但是它没有竖着的侧边栏丶而且ui稍微有点丑...

可以选择常驻所有页面或者划词的时候显示一次..
![【2019 03 14】【18∶11∶13】](https://user-images.githubusercontent.com/25548230/54349947-38dc4600-4687-11e9-9e13-62977cf60ae2.gif)
![【2019 03 14】【18∶53∶09】](https://user-images.githubusercontent.com/25548230/54351498-932ad600-468a-11e9-8ee5-0d3fff6a0cec.gif)

https://chrome.google.com/webstore/detail/searchbar/fjefgkhmchopegjeicnblodnidbammed
>>还有就是希望可以增加post和get两种引擎方式...

可以参考【Selection Search】
https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe

**Comment by RageCoke1466** [comment]
其实已经写好了但是是针对划词搜图的，最近在优化反向搜图，过两天就发布了

**Comment by 990721830** [comment]
划词搜图是什么鬼...
左键选中图片变蓝吗?

**Comment by RageCoke1466** [comment]
关键词多引擎搜图啦，

**Comment by 990721830** [comment]
嘤嘤嘤...
只有搜图吗?
到时候发布了在看吧...

**Comment by RageCoke1466** [comment]
嗯嗯可能会慢点，因为有很多文档之类的需要补充，
