### ISSUE TITLE
请教如何过滤掉二次元图片?

### ISSUE THREAD

**Issue by joshatt** [AInoob/NooBox#70]
**描述 Bug*
Bug 的具体状况是什么样的

**期望的行为是怎么样的**
正常的行为应该如何的

**截图**
如果有Bug 截图可以提供，最好提供一下

**平台 (提供完整信息):**
 - 浏览器 [e.g. Chrome，QQ浏览器，360 极速浏览器等等]

**额外信息**
其他信息需要我们知道的

在chrome商店看到有人说可以过滤掉结果中的二次元图片, 试了试没有找到方法. 请教

**Comment by bestpika** [comment]
把部分結果關掉，像是 SauceNAO、Ascii2D、IQDB

**Comment by joshatt** [comment]
@bestpika  多谢了. 以前没有注意过设置

**Comment by RageCoke1466** [comment]
多谢！@bestpika
