### ISSUE TITLE
百度识图换网址了无法搜索

### ISSUE THREAD

**Issue by oicqbak** [AInoob/NooBox#71]
**描述 Bug*
百度识图的BaseURL变更

"Baidu":"https://graph.baidu.com/upload?image={%s}&tn=pc&from=pc&image_source=PC_UPLOAD_URL"

另外还有搜狗和360识图，希望整合进去，谢谢~

这样就有10个搜图引擎了

**Comment by Shssaber** [comment]
百度识图确实用不了

**Comment by AInoob** [comment]
的确用不了，待修复中。。。

**Comment by AInoob** [comment]
Hello，应该修复了，如果还有问题可以reopen这个issue

**Comment by cooper1x** [comment]
还是不能用啊

**Comment by cooper1x** [comment]
![image](https://user-images.githubusercontent.com/9080789/62473163-c9502a00-b7d2-11e9-9689-150eab5ef3ce.png)
你看这个图，就没有百度的结果，只有百度可以搜到。

**Comment by AInoob** [comment]
嗨，我试了一下，如果你选择再次上传图片，就可以了。所以我猜测应该是图片的链接是墙外的，所以不能搜到。不过百度结果的图片炸了，会尝试修复的
