### ISSUE TITLE
更新下关于Noobox，Update Info about Noobox

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#72]
**首先感谢大家支持二箱**
1.最近没有更新的原因
2.二箱的现状
3.二箱的发展

1. 去年暑假，重写了二箱的以图搜图部分，花了不少时间，刚更新的时候，也是自己没有经验，连测试版都没有直接上线了，  = 。= 还好大家比较宽容，一个多月的修修补补基本上稳定了，感谢AInoob也没有骂我哈哈哈。12月毕业，就开始找工作什么的，生活方面很不不稳定，即使有时间，重心也不在二箱上。 不过还好，4月份以后就会稳定下来，就会有时间更新二箱。

2. 二箱的现状，二箱刚开始的时候，用纯React+ JS 写的，所以不好维护，去年采用React + DVA + Antd重写后，界面，功能，维护性都有提升，用的人越来越多了，表示很开心。 不过，因为当时是刚开始弄 Redux这些东西，代码质量确实不行。说完代码方面再说下功能方面，二箱初衷是工具箱，以图搜图的功能是所有工具里面用的人最多的，但是还有其他功能，但是其他功能用的人不是很多。但是在开发中，如果要重写一个功能，其他功能至少也要保持一致性，所以就要连带更新代码什么的，这样就会很花时间。

3. 二箱的发展，代码方面，我跟Ainoob讨论，可能再重写，采用更加轻量级的框架Mobx+ TypeScript，二箱主旨是工具箱，所以我们希望我的想法是看长远。 功能方向，可能把意图搜图拿出来来单独发展，二箱的以图搜图保持维护，更新新功能可能暂时不会考虑。然后Ainoob主要负责服务器那边，然后我负责插件的编写，这个新插件的期望是专注图片搜索，所以会集成 **关键词多引擎搜图**，跟 **反向多引擎搜图**， 反向搜图引擎目标是增加到12个，在二箱基础上增加了360， 搜狗，淘宝，Reddit搜图。

**First of all, thank you for supporting Noobox**
1. Reasons for no updates
2. The current situation of Noobox
3. The plan for Noobox

1. Last summer, I spent a lot of time to rewrite the Noobox. When updated, since without too much I experience. Directly online without alpha version, = . = Fortunately, users are tolerant. After more than a month of patching, Noobox stable now.  After graduating in December, I started looking for a job. Even if I have time, my focus is not on the Noobox. But fortunately, my life will be stable after April. Thus, there will be more time to update the Noobox.

2. The current situation of Noobox, Noobox was written with pure React+JS at the beginning, so it is not easy to maintain. After rewriting with React + DVA + Antd last year, the interface, function and maintenance have been improved. I am very happy that more and more people are using our extension. However, because at the time it was just beginning to get Redux, the quality of the code really didn't work. Talking about the coding, main body Noobox  is toolbox. Search By Image is popular comparing to other tool. However, in development, if you want to rewrite a function, other functions must be kept consistent, so it is necessary to update the code or something, which takes lots of time.

3. The plan of Noobox,  we may rewritten Noobox again for long-term benefits, such as code quality and maintenance, using the more lightweight framework Redux+ TypeScript. "Search By Image" may be developed as an independent extension. Ainoob is mainly responsible for the server side, then I am responsible for updating the extension. The expectation of this new plugin is to focus on image search, so it will integrate ** keyword multi-engine search **, and ** reverse multi-engine search ** The engines of the reverse search engine are increased to 12, and 360, Sogou, Taobao, and Reddit.

**Comment by zy410419243** [comment]
TypeScript 是很必要，但 redux 真的有必要么...现在看上去状态其实也不太复杂，反而是写 action 比较绕了

还有就是 `styled-components`，css 还是独立出来好看点，构建的时候合进 js 就完了

**Comment by RageCoke1466** [comment]
是的，换成轻量的mobox

**Comment by oicqbak** [comment]
所以快更新了吧，哈哈

**Comment by RageCoke1466** [comment]
独立的搜图插件更新了
