### ISSUE TITLE
ImgScope Alpha Release, ImgScope 预览版

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#75]
Noobox 的搜图功能被提取了出来，做成新的 extension - ImgScope，预览版版下载链接放在下面，大家可以试试，欢迎提意见，目前预览版有不少小bug，正在努力修复中，代码在正式版发布时候放出，

新功能
 - 新设计
- 关键词多引擎搜图
- 关键词粘贴板功能
 - 增加到11个引擎
 - 自动去除加载失败图片（设置中开启）

http://ainoob.com/ImageScope_V1.0.0.0_Alpha.crx

"Search by Image" function is separated from Noobox, ImgScope will be the name of the new Extension. Link of Alpha version will be putted in this issue

New functionality 
- New Design
- Mulit-Engine Search By Keyword 
- Clipboard for Search By Keyword
- Increase Engines of Search By Image to 11
- Auto remove loading failed Image

http://ainoob.com/ImageScope_V1.0.0.0_Alpha.crx

**Comment by bestpika** [comment]
1. 在背景分頁搜尋
2. 搜尋引擎開關←這看起來只是現在還沒做好而已？
