### ISSUE TITLE
ImgScope预览版bug

### ISSUE THREAD

**Issue by oicqbak** [AInoob/NooBox#76]
刚刚测试下，百度识图修复了，新增的搜狗和360也都使用正常。

一、但在“图镜”搜索页面，顶部点击“搜索引擎”单独搜索

①.百度无法跳转识图：{"status":0,"msg":"Success","data":{"url":……

②360和淘宝或无法点击：关闭ascii2d的前提下

③360和淘宝或跳转ascii2d网址404：开启ascii2d的前提下

④ascii2d 显示404

二、用“←”隐藏搜索引擎开关很漂亮，但也过于隐蔽，建议在插件说明里注明

三、反馈链接暂时没有，以后加入“图镜”独立github页面？

**Comment by RageCoke1466** [comment]
谢谢反馈！要重新建立 Repo，测试版是我赶出来的，还有蛮多问题的，正常功能可以用，但是小问题蛮多的，会一一修复的，
