### ISSUE TITLE
ImgScope Bug收集与修复进度

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#77]
- [x] 百度，360，淘宝，搜索结果页，链接失效，无法跳转识图 @oicqbak 
- [x] Ascii2d, 引擎开启引起的连锁反应 @oicqbak 
- [x] 关键词搜图，右键快捷搜索失效
- [x] 优化设置引擎按钮
- [ ] 优化设置命名

**Comment by oicqbak** [comment]
另外“截图搜索”失效了？

**Comment by RageCoke1466** [comment]
应该是设置哪个地方没移植好

**Comment by oicqbak** [comment]
这是快要出正式版了吧~

**Comment by RageCoke1466** [comment]
是的，可能再发一个测试版（beta），哈哈哈，上周末努力修复来着，bug 都修的差不多了，现在在弄 新版本chrome 兼容

**Comment by zhtw2013** [comment]
那翻譯修改怎辦 到時重弄嗎

**Comment by RageCoke1466** [comment]
语言包还好，反向搜图的语言包都保留着的，然后新添加的功能，如果看到有翻译不合适的，我们可以再沟通更改
