### ISSUE TITLE
繁体语言文件

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBox#8]
抱歉，昨晚睡着了没弄好..

[NooBox zh_TW.zip](https://github.com/AInoob/NooBox/files/1283419/NooBox.zh_TW.zip)

About繁体也弄好了(放在zip里)，要麻烦作者自己提取，偶不会写程序...

少年在台湾，不在西雅图，喝不到作者请的咖啡了...哈

**Comment by AInoob** [comment]
感谢感谢！最近工作有点累，周末会更新的～

**Comment by AInoob** [comment]
已经支持繁体中文，版本0.9.3.9～
