### ISSUE TITLE
"Image Scope" Beta Release, 图镜 测试版

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#81]
Image Scope 
谢谢大家提的意见，测试版已经完成，下载链接在下方

更改以及修复
- [x] 百度，360，淘宝，搜索结果页，链接失效，无法跳转识图 @oicqbak 
- [x] Ascii2d, 引擎开启引起的连锁反应 @oicqbak 
- [x] 关键词搜图，右键快捷搜索失效
- [x] 优化设置引擎按钮
- [x] 优化设置命名

http://ainoob.com/ImageScope@BetaV1.0.0.crx

**Comment by bestpika** [comment]
404 Not found.

**Comment by oicqbak** [comment]
Page not found · GitHub

**Comment by RageCoke1466** [comment]
换了个链接，应该可以了

**Comment by oicqbak** [comment]
> 换了个链接，应该可以了

win10 Cent Browser(Chromium 74.0.3729.157)初步测试

1、右键菜单无法自动启用（先关闭“开启以图搜图”的开关，再打开才会出现右键菜单）
2、提取图片 失效
3、截图搜索 失效
4、记录历史图片 失效
5、自动移除加载失败图片（部分未移除）

可能是浏览器版本过低了？

**Comment by bestpika** [comment]
那個自動複製關鍵詞是指自動讀取剪貼簿的關鍵詞？

**Comment by bestpika** [comment]
IQDB 的結果沒有連結可以點
![image](https://user-images.githubusercontent.com/5698157/58450157-50808200-8140-11e9-9221-07defa69c84b.png)

**Comment by RageCoke1466** [comment]
是的，这个暂时没有加入，自动复制关键词是，自动读取剪贴板关键词 @bestpika

**Comment by RageCoke1466** [comment]
是不是跟你的浏览器有关系，我用Chrome都可以 @bestpika

**Comment by bestpika** [comment]
擴充套件說明還沒改
![image](https://user-images.githubusercontent.com/5698157/58450276-cf75ba80-8140-11e9-8e5c-b6a0eeeed370.png)

**Comment by RageCoke1466** [comment]
是的，语言包里面还没动，还有些二箱的东西

**Comment by RageCoke1466** [comment]
初始化会有个设定 Bug，所以一上来各种设定都没有，立马修复，立马发Beta3，谢谢 @oicqbak

**Comment by RageCoke1466** [comment]
已修复 @oicqbak
