### ISSUE TITLE
"Img Scope" Beta4 Release, 图镜 测试版4

### ISSUE THREAD

**Issue by RageCoke1466** [AInoob/NooBox#83]
谢谢大家帮忙测试，第二个测试版放出，正式版预计下周出来，现在正在补充doc

- [x] 矫正语言包

- [x] 删除，特别感谢，还有介绍（这两项会放在 接下来的介绍 网页里面）

- [x] 修改名字，从ImageScope 变成 ImgScope

- [x] 修改初始设定Bug

Thanks for everyone, Second Beta release

- [x] Correct Locale

- [x] Delete About, Special( will be showed in a separate page)

- [x] Change Name from ImageScope to ImgScope

- [x] Fix Initial Setting Bug

https://ainoob.com/ImgScope@Beta4V1.0.0.crx

**Comment by oicqbak** [comment]
Sorry, that page was not found.

**Comment by RageCoke1466** [comment]
弄好了

**Comment by oicqbak** [comment]
> 弄好了

(Chromium 74.0.3729.169)测试            

安装后有右键菜单，重启浏览器就没有右键菜单

**Comment by RageCoke1466** [comment]
嗯嗯 我明天再弄下，那个cent浏览器估计可以用，对官方文档里面api理解还是不是很准确，明天再研究下

oicqbak <notifications@github.com> 于 2019年6月3日周一 下午11:34写道：

**Comment by RageCoke1466** [comment]
@oicqbak 已经修复，我在我的电脑上测试了一下，应该没有问题了

**Comment by oicqbak** [comment]
> @oicqbak已经修复，我在我的电脑上测试了一下，应该没有问题了

Cent Browser可以使用了，但有3个问题。

1，记录历史图片失效（去掉√，依然保留历史）
2，截图搜索失效（点击没有截图框选）
3，自动移除加载失败图片（部分未移除，可能是部分网站被墙？）

**Comment by RageCoke1466** [comment]
好的
1. 记录历史失效，这个已经修复
2. 这个要具体看，能不能告诉我哪个网站不行，我试了淘宝是可以的
3. 能不能告诉我下哪个引擎，移除失败了，或者能发你搜的图片到我邮箱，ragecoke@ainoob.com

**Comment by oicqbak** [comment]
> 好的
> 
> 1. 记录历史失效，这个已经修复
> 2. 这个要具体看，能不能告诉我哪个网站不行，我试了淘宝是可以的
> 3. 能不能告诉我下哪个引擎，移除失败了，或者能发你的搜索图片到我邮箱，[ragecoke @ anoob.com](mailto:ragecoke@ainoob.com)

2.是所有的网站（点击后没反应，没有出现像QQ截图的鼠标。可能是浏览器兼容性问题）
3.谷歌引擎（会出现很大的黑色，照片破裂的图片）
![QQ截图20190606123511](https://user-images.githubusercontent.com/48817040/59007086-8d8ef780-8857-11e9-891f-b002b4d1618a.png)

**Comment by RageCoke1466** [comment]
好的，我研究一下

**Comment by oicqbak** [comment]
> 好的我研究一下，还有这个引擎图片在你电脑上的显示比例有点失衡呢，是放大了吗

![QQ截图20190606132906](https://user-images.githubusercontent.com/48817040/59009167-1bbaac00-885f-11e9-86e6-93471d99c8a7.png)

浏览器100%

**Comment by RageCoke1466** [comment]
历史记录问题，跟UI问题修复了，@oicqbak ，截图问题，好像没有找到，我这边无法复现
