### ISSUE TITLE
想要 Firefox 支持

### ISSUE THREAD

**Issue by Zhang-Siyang** [AInoob/NooBox#84]

**Comment by RageCoke1466** [comment]
Firefox, 其实应该不会麻烦因为API都差不多了，只是需要人维护，等我发布ImgScope，看看能不能先弄个Beta的Fireefox，

**Comment by AInoob** [comment]
Hey，FireFox已经有了～
https://addons.mozilla.org/en-US/firefox/addon/noobox_2

**Comment by mzji** [comment]
大佬，在 Github 和各入口介绍页面也添加一下 Firefox 安装地址如何？
