### ISSUE TITLE
Storage of images used in Noobox Search in Computer

### ISSUE THREAD

**Issue by zarst990** [AInoob/NooBox#85]
Sorry that I'm not really asking about a bug, but more of an inquiry.

Is there a place in the local repository where the images used for Noobox Searches are stored? Or do they use images from the browsers' cache?

Because I'm trying to access previous searches but they are unavailable

**Comment by RageCoke1466** [comment]
Yeah, In the Extension Page -> Find Noobox -> Detail -> "Inspect views" -> background page -> Application -> IndexDB
