### ISSUE TITLE
想提个 想法 

### ISSUE THREAD

**Issue by lhj5426** [AInoob/NooBox#87]
是这样的 2箱的主体是 浏览器的搜图扩展
主要是在浏览器上进行搜图
作者 有没有考虑过
如果是在QQ群里看到图之后搜图的步骤有点繁琐呢
QQ群里看到图片 先 保存到本地  或者截图保存到本地 然后打开浏览器然后 用二箱上传搜索
步骤有点多 能不能给二箱做一个衔接图片URL的功能呢

大概是这个样子

QQ群里看到图片  用sharex 或者同类型的截图工具 进行截图 截图之后会自动上传到图床
返回一个 图床外链的URL 
二箱如果能给个 接口 
可以 衔接一下 
二箱接口 衔接   截图软件返回来的URL

这样可以实现 免 保存本地直接 截图 搜图一气呵成的操作 省去了中间步骤 
这种功能可以实现么  这种操作没有割裂感

目前是用AHK 来实现这种效果 因为 搜图网站可以直接给URL来搜图 

如果2箱可以 衔接URL 那 吊炸天0 0 太 方便了

![image](https://user-images.githubusercontent.com/30548000/59973986-243e1100-95d9-11e9-9556-df5b308bb8c3.png)
****

**Comment by lhj5426** [comment]
2箱的多个网站聚合显示搜索结果简直太方便了。。。。。

**Comment by RageCoke1466** [comment]
哈哈哈，静静等待Chrome开放更多浏览器权限，才能做这种操作，跨App相当于系统操作

**Comment by AInoob** [comment]
Hello，二箱其实是有一个类似图床的服务的，不过只保存最近一小部分图片。所以基本上几分钟到一个小时就失效了。暂时没有考虑开放接口也是这个原因。
目前来看的话，接口虽然在那里，但是暂时不考虑开放，毕竟只有短暂的存活时间，一旦被覆盖，就没有了。
