### ISSUE TITLE
Yandex 搜图返回400 bad request，链接需要更改

### ISSUE THREAD

**Issue by Engiun** [AInoob/NooBox#88]
如题，yandex 搜图获取不到结果，手动点开会返回400 bad request，
看了下把二箱搜图链接字符串https://www.yandex.com/images/search?xxx里面的
www.yandex.com 改成 yandex.com。这样就能获取到正常结果。请修改，非常感谢~

**Comment by oicqbak** [comment]
二箱估计不会更新，试试新作
“Img Scope”Beta 5 Release，图镜测试版5

链接下载
https://ainoob.com/ImgScope@Beta5V1.0.0.crx

**Comment by AInoob** [comment]
Hello，好久没来看了。我这里测试Yandex可以正常访问，你可以再确认一次吗？

**Comment by AlphaAnother** [comment]
作者你好 我这边也有这种情况 会出现400错误 可以添加一个开关选择用yandex.com来替换www.yandex.com吗？

**Comment by cilone** [comment]
遇到同样问题~~

**Comment by Noah1995** [comment]
> Hello，好久没来看了。我这里测试Yandex可以正常访问，你可以再确认一次吗？

我也这样yandex.com来替换www.yandex.com可以解决

**Comment by AInoob** [comment]
Hello，之前修复了，抱歉拖更～
