### ISSUE TITLE
yandex无法使用

### ISSUE THREAD

**Issue by SpiceHORO** [AInoob/NooBox#89]
**描述 Bug*
Bug 的具体状况是什么样的
上传图片后没有反应
**期望的行为是怎么样的**
正常的行为应该如何的
打开搜图标签页
**截图**
如果有Bug 截图可以提供，最好提供一下

**平台 (提供完整信息):**
 - 浏览器 [e.g. Chrome，QQ浏览器，360 极速浏览器等等]
Yandex 19.6.2.599
**额外信息**
其他信息需要我们知道的

**Comment by AInoob** [comment]
Hi，问题应该之前就修复了，感谢反馈～

**Comment by SpiceHORO** [comment]
> Hi，问题应该之前就修复了，感谢反馈～

Yandex 19.12.0.358
上传图片还是没反应，历史页面也没显示上传的记录。在网页图片上右击倒是可以“搜索这张图片”

**Comment by AInoob** [comment]
了解。。。原来你说的是yandex浏览器啊。我明天测试一下。
