### ISSUE TITLE
无法使用二箱的提取图片

### ISSUE THREAD

**Issue by dalade** [AInoob/NooBox#91]
**描述 Bug*
Bug 的具体状况是什么样的
近期360极速浏览器无法使用二箱的提取图片，放到谷歌浏览器倒是可以用，确定不是网页自身不能提取的问题。
**期望的行为是怎么样的**
正常的行为应该如何的

**截图**
如果有Bug 截图可以提供，最好提供一下

**平台 (提供完整信息):**
 - 浏览器 [e.g. Chrome，QQ浏览器，360 极速浏览器等等]

**额外信息**
其他信息需要我们知道的

**Comment by AInoob** [comment]
嗨，我先关闭这个了。如果还有问题欢迎reopen.
